import type { TriviaQuestion } from '../types'

export const ANIMALS_QUESTIONS: TriviaQuestion[] = [
  {
    id: 'ani-d1-1',
    category: 'animals',
    difficulty: 1,
    question: 'What is the largest mammal on Earth?',
    choices: ['Elephant', 'Blue whale', 'Giraffe', 'Polar bear'],
    correctIndex: 1,
  },
  {
    id: 'ani-d1-2',
    category: 'animals',
    difficulty: 1,
    question: 'How many legs does a spider have?',
    choices: ['6', '8', '10', '12'],
    correctIndex: 1,
  },
  {
    id: 'ani-d2-1',
    category: 'animals',
    difficulty: 2,
    question: 'Which bird is known for mimicking human speech?',
    choices: ['Crow', 'Parrot', 'Owl', 'Eagle'],
    correctIndex: 1,
  },
  {
    id: 'ani-d2-2',
    category: 'animals',
    difficulty: 2,
    question: 'A group of lions is called a what?',
    choices: ['Pack', 'Herd', 'Pride', 'Flock'],
    correctIndex: 2,
  },
  {
    id: 'ani-d3-1',
    category: 'animals',
    difficulty: 3,
    question: 'Which animal has the longest neck?',
    choices: ['Ostrich', 'Giraffe', 'Camel', 'Emu'],
    correctIndex: 1,
  },
  {
    id: 'ani-d3-2',
    category: 'animals',
    difficulty: 3,
    question: 'What is a baby kangaroo called?',
    choices: ['Cub', 'Joey', 'Pup', 'Calf'],
    correctIndex: 1,
  },
  {
    id: 'ani-d4-1',
    category: 'animals',
    difficulty: 4,
    question: 'Which mammal lays eggs?',
    choices: ['Koala', 'Platypus', 'Wombat', 'Sloth'],
    correctIndex: 1,
  },
  {
    id: 'ani-d4-2',
    category: 'animals',
    difficulty: 4,
    question: 'Octopuses have how many hearts?',
    choices: ['1', '2', '3', '4'],
    correctIndex: 2,
  },
  {
    id: 'ani-d5-1',
    category: 'animals',
    difficulty: 5,
    question: 'Which tiny animal is famous for surviving extreme cold, radiation, and even the vacuum of space?',
    choices: ['Ant', 'Tardigrade', 'Cockroach', 'Bee'],
    correctIndex: 1,
  },
  {
    id: 'ani-d5-2',
    category: 'animals',
    difficulty: 5,
    question: 'The axolotl is native to lakes near which world city?',
    choices: ['Lima', 'Mexico City', 'Bangkok', 'Cairo'],
    correctIndex: 1,
  },
]
