import type { TriviaQuestion } from '../types'

export const GENERAL_QUESTIONS: TriviaQuestion[] = [
  {
    id: 'gen-d1-1',
    category: 'general',
    difficulty: 1,
    question: 'How many continents are there on Earth?',
    choices: ['5', '6', '7', '8'],
    correctIndex: 2,
  },
  {
    id: 'gen-d1-2',
    category: 'general',
    difficulty: 1,
    question: 'What is the capital of France?',
    choices: ['Lyon', 'Marseille', 'Paris', 'Nice'],
    correctIndex: 2,
  },
  {
    id: 'gen-d2-1',
    category: 'general',
    difficulty: 2,
    question: 'The Panama Canal connects which two oceans?',
    choices: ['Atlantic & Indian', 'Pacific & Indian', 'Atlantic & Pacific', 'Arctic & Pacific'],
    correctIndex: 2,
  },
  {
    id: 'gen-d2-2',
    category: 'general',
    difficulty: 2,
    question: 'What is the smallest independent country by area?',
    choices: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'],
    correctIndex: 1,
  },
  {
    id: 'gen-d3-1',
    category: 'general',
    difficulty: 3,
    question: 'The Richter scale measures the magnitude of what?',
    choices: ['Hurricanes', 'Earthquakes', 'Volcanic eruptions', 'Tsunamis'],
    correctIndex: 1,
  },
  {
    id: 'gen-d3-2',
    category: 'general',
    difficulty: 3,
    question: 'Which language has the most native speakers worldwide?',
    choices: ['English', 'Spanish', 'Mandarin Chinese', 'Hindi'],
    correctIndex: 2,
  },
  {
    id: 'gen-d4-1',
    category: 'general',
    difficulty: 4,
    question: 'Besides mercury, which element is liquid at room temperature?',
    choices: ['Gallium', 'Bromine', 'Cesium', 'Francium'],
    correctIndex: 1,
  },
  {
    id: 'gen-d4-2',
    category: 'general',
    difficulty: 4,
    question: 'How many time zones does mainland China officially use?',
    choices: ['1', '3', '5', '8'],
    correctIndex: 0,
  },
  {
    id: 'gen-d5-1',
    category: 'general',
    difficulty: 5,
    question: 'Which country spans the most time zones (including territories)?',
    choices: ['United States', 'Russia', 'France', 'China'],
    correctIndex: 2,
  },
  {
    id: 'gen-d5-2',
    category: 'general',
    difficulty: 5,
    question: 'Which chess opening begins 1.e4 e5 2.Nf3 Nc6 3.Bb5?',
    choices: ['Sicilian Defense', 'Ruy López', "Queen's Gambit", 'French Defense'],
    correctIndex: 1,
  },
]
