import type { TriviaQuestion } from '../types'

export const HISTORY_QUESTIONS: TriviaQuestion[] = [
  {
    id: 'his-d1-1',
    category: 'history',
    difficulty: 1,
    question: 'Who was the first President of the United States?',
    choices: ['Thomas Jefferson', 'George Washington', 'John Adams', 'Benjamin Franklin'],
    correctIndex: 1,
  },
  {
    id: 'his-d1-2',
    category: 'history',
    difficulty: 1,
    question: 'Ancient Egyptian rulers were called what?',
    choices: ['Emperors', 'Pharaohs', 'Sultans', 'Tsars'],
    correctIndex: 1,
  },
  {
    id: 'his-d2-1',
    category: 'history',
    difficulty: 2,
    question: 'In which year did World War II end?',
    choices: ['1943', '1944', '1945', '1946'],
    correctIndex: 2,
  },
  {
    id: 'his-d2-2',
    category: 'history',
    difficulty: 2,
    question: 'The Great Wall was built primarily in which country?',
    choices: ['Japan', 'China', 'Korea', 'Mongolia'],
    correctIndex: 1,
  },
  {
    id: 'his-d3-1',
    category: 'history',
    difficulty: 3,
    question: 'Which ship sank in 1912 after hitting an iceberg?',
    choices: ['Lusitania', 'Titanic', 'Britannic', 'Olympic'],
    correctIndex: 1,
  },
  {
    id: 'his-d3-2',
    category: 'history',
    difficulty: 3,
    question: 'The Renaissance began in which European country?',
    choices: ['France', 'England', 'Italy', 'Spain'],
    correctIndex: 2,
  },
  {
    id: 'his-d4-1',
    category: 'history',
    difficulty: 4,
    question: 'The Magna Carta was signed in which century?',
    choices: ['11th', '12th', '13th', '14th'],
    correctIndex: 2,
  },
  {
    id: 'his-d4-2',
    category: 'history',
    difficulty: 4,
    question: 'Which empire was ruled by Genghis Khan?',
    choices: ['Ottoman', 'Mongol', 'Persian', 'Byzantine'],
    correctIndex: 1,
  },
  {
    id: 'his-d5-1',
    category: 'history',
    difficulty: 5,
    question: 'The Treaty of Westphalia (1648) is often cited as the birth of what concept?',
    choices: ['Colonialism', 'Modern nation-states', 'Feudalism', 'Mercantilism'],
    correctIndex: 1,
  },
  {
    id: 'his-d5-2',
    category: 'history',
    difficulty: 5,
    question: 'Which Byzantine empress restored icon veneration after the Iconoclast controversy?',
    choices: ['Theodora', 'Irene of Athens', 'Zoe', 'Theophano'],
    correctIndex: 1,
  },
]
