import type { TriviaQuestion } from '../types'

export const LITERATURE_QUESTIONS: TriviaQuestion[] = [
  {
    id: 'lit-d1-1',
    category: 'literature',
    difficulty: 1,
    question: 'Who wrote "Harry Potter"?',
    choices: ['J.R.R. Tolkien', 'J.K. Rowling', 'C.S. Lewis', 'Roald Dahl'],
    correctIndex: 1,
  },
  {
    id: 'lit-d1-2',
    category: 'literature',
    difficulty: 1,
    question: 'In "The Three Little Pigs," what did the third pig build his house from?',
    choices: ['Straw', 'Sticks', 'Bricks', 'Stone'],
    correctIndex: 2,
  },
  {
    id: 'lit-d2-1',
    category: 'literature',
    difficulty: 2,
    question: 'Who wrote "Romeo and Juliet"?',
    choices: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain'],
    correctIndex: 1,
  },
  {
    id: 'lit-d2-2',
    category: 'literature',
    difficulty: 2,
    question: 'What is the first book of the Bible?',
    choices: ['Exodus', 'Genesis', 'Psalms', 'Matthew'],
    correctIndex: 1,
  },
  {
    id: 'lit-d3-1',
    category: 'literature',
    difficulty: 3,
    question: 'Who wrote "1984"?',
    choices: ['Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'Kurt Vonnegut'],
    correctIndex: 1,
  },
  {
    id: 'lit-d3-2',
    category: 'literature',
    difficulty: 3,
    question: 'In Greek mythology, who stole fire for humanity?',
    choices: ['Zeus', 'Prometheus', 'Hermes', 'Apollo'],
    correctIndex: 1,
  },
  {
    id: 'lit-d4-1',
    category: 'literature',
    difficulty: 4,
    question: 'Which novel begins "It was the best of times, it was the worst of times"?',
    choices: ['Great Expectations', 'A Tale of Two Cities', 'Oliver Twist', 'David Copperfield'],
    correctIndex: 1,
  },
  {
    id: 'lit-d4-2',
    category: 'literature',
    difficulty: 4,
    question: 'Who wrote "One Hundred Years of Solitude"?',
    choices: ['Jorge Luis Borges', 'Gabriel García Márquez', 'Pablo Neruda', 'Isabel Allende'],
    correctIndex: 1,
  },
  {
    id: 'lit-d5-1',
    category: 'literature',
    difficulty: 5,
    question: 'Which epic poem opens with the line "Sing, O goddess, the anger of Achilles"?',
    choices: ['The Odyssey', 'The Iliad', 'The Aeneid', 'Beowulf'],
    correctIndex: 1,
  },
  {
    id: 'lit-d5-2',
    category: 'literature',
    difficulty: 5,
    question: 'In Joyce’s "Ulysses," Leopold Bloom’s day mirrors which classical epic?',
    choices: ['The Iliad', 'The Odyssey', 'The Aeneid', 'Metamorphoses'],
    correctIndex: 1,
  },
]
