import type { TriviaQuestion } from '../types'

export const NINETIES_QUESTIONS: TriviaQuestion[] = [
  {
    id: '90s-1',
    category: 'nineties',
    question: 'Who sang "Smells Like Teen Spirit"?',
    choices: ['Pearl Jam', 'Nirvana', 'Soundgarden', 'Alice in Chains'],
    correctIndex: 1,
  },
  {
    id: '90s-2',
    category: 'nineties',
    question: 'Which sitcom followed six friends in New York City?',
    choices: ['Seinfeld', 'Friends', 'Frasier', 'Cheers'],
    correctIndex: 1,
  },
  {
    id: '90s-3',
    category: 'nineties',
    question: 'Who played Neo in The Matrix (1999)?',
    choices: ['Brad Pitt', 'Keanu Reeves', 'Tom Cruise', 'Will Smith'],
    correctIndex: 1,
  },
  {
    id: '90s-4',
    category: 'nineties',
    question: 'What portable music player did Apple release in 2001?',
    choices: ['Walkman', 'Zune', 'iPod', 'Discman'],
    correctIndex: 2,
  },
  {
    id: '90s-5',
    category: 'nineties',
    question: 'Which dance song is associated with the Macarena?',
    choices: ['Los del Río', 'Village People', 'Spice Girls', 'Backstreet Boys'],
    correctIndex: 0,
  },
  {
    id: '90s-6',
    category: 'nineties',
    question: 'Tamagotchi was a popular 90s…',
    choices: ['Video game console', 'Virtual pet', 'Boy band', 'Snack food'],
    correctIndex: 1,
  },
  {
    id: '90s-7',
    category: 'nineties',
    question: 'Which boy band released "I Want It That Way" in 1999?',
    choices: ['NSYNC', 'Backstreet Boys', 'Boyz II Men', 'New Kids on the Block'],
    correctIndex: 1,
  },
  {
    id: '90s-8',
    category: 'nineties',
    question: 'The TV show "The Fresh Prince of Bel-Air" starred…',
    choices: ['Will Smith', 'Eddie Murphy', 'Chris Rock', 'Dave Chappelle'],
    correctIndex: 0,
  },
  {
    id: '90s-9',
    category: 'nineties',
    question: 'Which movie featured dinosaurs brought back by DNA?',
    choices: ['Jumanji', 'Jurassic Park', 'Godzilla', 'The Lost World'],
    correctIndex: 1,
  },
  {
    id: '90s-10',
    category: 'nineties',
    question: 'Pokémon Red and Blue launched in the US in…',
    choices: ['1994', '1996', '1998', '2000'],
    correctIndex: 2,
  },
  {
    id: '90s-11',
    category: 'nineties',
    question: 'Who was president of the United States for most of the 1990s?',
    choices: ['George H. W. Bush', 'Bill Clinton', 'George W. Bush', 'Ronald Reagan'],
    correctIndex: 1,
  },
  {
    id: '90s-12',
    category: 'nineties',
    question: 'The phrase "Talk to the hand" became popular after which film?',
    choices: ['Clueless', 'Titanic', 'Home Alone', 'Speed'],
    correctIndex: 0,
  },
  {
    id: '90s-13',
    category: 'nineties',
    question: 'Which console launched with "Super Mario 64"?',
    choices: ['PlayStation', 'Nintendo 64', 'Sega Saturn', 'Game Boy Color'],
    correctIndex: 1,
  },
  {
    id: '90s-14',
    category: 'nineties',
    question: 'Spice Girls hit "Wannabe" urged listeners to tell you what they want, what they really really want…',
    choices: ['Now', 'Later', 'Never', 'Maybe'],
    correctIndex: 0,
  },
  {
    id: '90s-15',
    category: 'nineties',
    question: 'Which animated series featured Bart, Lisa, and Maggie?',
    choices: ['Family Guy', 'The Simpsons', 'South Park', 'Beavis and Butt-Head'],
    correctIndex: 1,
  },
  {
    id: '90s-16',
    category: 'nineties',
    question: 'The "Rachel" haircut was popularized by which actress on Friends?',
    choices: ['Courteney Cox', 'Jennifer Aniston', 'Lisa Kudrow', 'Julia Roberts'],
    correctIndex: 1,
  },
  {
    id: '90s-17',
    category: 'nineties',
    question: 'Which search engine dominated the early web before Google?',
    choices: ['Yahoo', 'Ask Jeeves', 'AltaVista', 'All of the above were huge'],
    correctIndex: 3,
  },
  {
    id: '90s-18',
    category: 'nineties',
    question: 'Titanic (1997) won how many Academy Awards?',
    choices: ['5', '8', '11', '14'],
    correctIndex: 2,
  },
]
