import type { TriviaQuestion } from '../types'

export const POPCULTURE_QUESTIONS: TriviaQuestion[] = [
  {
    id: 'pop-d1-1',
    category: 'popculture',
    difficulty: 1,
    question: 'What company makes the iPhone?',
    choices: ['Samsung', 'Google', 'Apple', 'Microsoft'],
    correctIndex: 2,
  },
  {
    id: 'pop-d1-2',
    category: 'popculture',
    difficulty: 1,
    question: 'Which superhero is known as the "Man of Steel"?',
    choices: ['Batman', 'Spider-Man', 'Superman', 'Iron Man'],
    correctIndex: 2,
  },
  {
    id: 'pop-d2-1',
    category: 'popculture',
    difficulty: 2,
    question: 'Which band sang "Bohemian Rhapsody"?',
    choices: ['The Beatles', 'Queen', 'Led Zeppelin', 'Pink Floyd'],
    correctIndex: 1,
  },
  {
    id: 'pop-d2-2',
    category: 'popculture',
    difficulty: 2,
    question: 'In "The Lion King," what is the name of Simba’s father?',
    choices: ['Scar', 'Mufasa', 'Rafiki', 'Zazu'],
    correctIndex: 1,
  },
  {
    id: 'pop-d3-1',
    category: 'popculture',
    difficulty: 3,
    question: 'Which TV show features the fictional coffee shop Central Perk?',
    choices: ['Seinfeld', 'Friends', 'How I Met Your Mother', 'The Office'],
    correctIndex: 1,
  },
  {
    id: 'pop-d3-2',
    category: 'popculture',
    difficulty: 3,
    question: 'Who directed "Jurassic Park" (1993)?',
    choices: ['James Cameron', 'Steven Spielberg', 'George Lucas', 'Ridley Scott'],
    correctIndex: 1,
  },
  {
    id: 'pop-d4-1',
    category: 'popculture',
    difficulty: 4,
    question: 'Which artist released the album "Thriller" in 1982?',
    choices: ['Prince', 'Michael Jackson', 'Madonna', 'Whitney Houston'],
    correctIndex: 1,
  },
  {
    id: 'pop-d4-2',
    category: 'popculture',
    difficulty: 4,
    question: 'In "Breaking Bad," what is Walter White’s alias?',
    choices: ['The Chemist', 'Heisenberg', 'Blue Sky', 'The Cook'],
    correctIndex: 1,
  },
  {
    id: 'pop-d5-1',
    category: 'popculture',
    difficulty: 5,
    question: 'Which film won the first Academy Award for Best Picture (1929 ceremony)?',
    choices: ['Sunrise', 'Wings', 'The Jazz Singer', 'Metropolis'],
    correctIndex: 1,
  },
  {
    id: 'pop-d5-2',
    category: 'popculture',
    difficulty: 5,
    question: 'Which Studio Ghibli film features a bathhouse run by the witch Yubaba?',
    choices: ['My Neighbor Totoro', 'Spirited Away', 'Princess Mononoke', 'Howl\'s Moving Castle'],
    correctIndex: 1,
  },
]
