import type { TriviaQuestion } from '../types'

export const SCIENCE_QUESTIONS: TriviaQuestion[] = [
  {
    id: 'sci-1',
    category: 'science',
    question: 'Which planet is known as the Red Planet?',
    choices: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
    correctIndex: 1,
  },
  {
    id: 'sci-2',
    category: 'science',
    question: 'What is the chemical symbol for gold?',
    choices: ['Go', 'Gd', 'Au', 'Ag'],
    correctIndex: 2,
  },
  {
    id: 'sci-3',
    category: 'science',
    question: 'How many bones are in an adult human body (approximately)?',
    choices: ['186', '206', '226', '256'],
    correctIndex: 1,
  },
  {
    id: 'sci-4',
    category: 'science',
    question: 'What gas do plants primarily absorb for photosynthesis?',
    choices: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
    correctIndex: 2,
  },
  {
    id: 'sci-5',
    category: 'science',
    question: 'What is the powerhouse of the cell?',
    choices: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi body'],
    correctIndex: 2,
  },
  {
    id: 'sci-6',
    category: 'science',
    question: 'Water boils at 100°C at standard pressure at…',
    choices: ['Sea level', 'Mount Everest peak', 'Deep ocean', 'Space vacuum'],
    correctIndex: 0,
  },
  {
    id: 'sci-7',
    category: 'science',
    question: 'What is the hardest natural substance on Earth?',
    choices: ['Quartz', 'Diamond', 'Topaz', 'Steel'],
    correctIndex: 1,
  },
  {
    id: 'sci-8',
    category: 'science',
    question: 'Which organ pumps blood through the body?',
    choices: ['Lungs', 'Liver', 'Heart', 'Kidneys'],
    correctIndex: 2,
  },
  {
    id: 'sci-9',
    category: 'science',
    question: 'DNA stands for…',
    choices: [
      'Deoxyribonucleic acid',
      'Dynamic nuclear acid',
      'Dual nitrogen array',
      'Dense nucleotide alloy',
    ],
    correctIndex: 0,
  },
  {
    id: 'sci-10',
    category: 'science',
    question: 'Light travels fastest in a…',
    choices: ['Vacuum', 'Water', 'Glass', 'Diamond'],
    correctIndex: 0,
  },
  {
    id: 'sci-11',
    category: 'science',
    question: 'Which element has atomic number 1?',
    choices: ['Helium', 'Hydrogen', 'Lithium', 'Carbon'],
    correctIndex: 1,
  },
  {
    id: 'sci-12',
    category: 'science',
    question: 'The human body is about what percent water?',
    choices: ['40%', '60%', '80%', '95%'],
    correctIndex: 1,
  },
  {
    id: 'sci-13',
    category: 'science',
    question: 'What force keeps planets in orbit around the Sun?',
    choices: ['Magnetism', 'Friction', 'Gravity', 'Inertia alone'],
    correctIndex: 2,
  },
  {
    id: 'sci-14',
    category: 'science',
    question: 'Which blood type is known as the universal donor?',
    choices: ['A+', 'B+', 'AB+', 'O−'],
    correctIndex: 3,
  },
  {
    id: 'sci-15',
    category: 'science',
    question: 'Sound cannot travel through a…',
    choices: ['Solid', 'Liquid', 'Gas', 'Vacuum'],
    correctIndex: 3,
  },
  {
    id: 'sci-16',
    category: 'science',
    question: 'Photosynthesis mainly produces…',
    choices: ['CO₂ and water', 'Oxygen and glucose', 'Nitrogen', 'Methane'],
    correctIndex: 1,
  },
  {
    id: 'sci-17',
    category: 'science',
    question: 'How many chromosomes do humans normally have?',
    choices: ['23', '46', '48', '92'],
    correctIndex: 1,
  },
  {
    id: 'sci-18',
    category: 'science',
    question: 'Which planet has the most moons in our solar system?',
    choices: ['Earth', 'Mars', 'Jupiter', 'Neptune'],
    correctIndex: 2,
  },
]
