// NSFW truth + dare lists for an adults-only (18+) party game.
// Sourced from the Truth or Dare "sexy" mode question lists.
export const TRUTHS: string[] = [
  "What's the most attractive quality in someone that has nothing to do with looks?",
  "What's the best kiss you've ever had and why?",
  "What's something that instantly puts you in the mood?",
  "What's your idea of a perfect date night?",
  "What's the most romantic or flirty thing someone has done for you?",
  "What's a turn-on you're a little embarrassed to admit?",
  "What's the sexiest compliment you've ever received?",
  "What's your favorite way to be touched?",
  "What's something you find attractive that most people don't?",
  "What's the most daring thing you've done for someone you liked?",
  "What's your wildest fantasy you'd actually try?",
  "What's the riskiest place you've ever hooked up or fooled around?",
  "What's the hottest text or DM you've ever sent or received?",
  "What's something that always gets you going no matter what?",
  "What body part on someone else turns you on the most?",
  "What's a song or movie scene that always turns you on?",
  "What's the most spontaneous sexual thing you've ever done?",
  "What's one thing you've always wanted to try in bed?",
  "What's the most attractive outfit you've seen someone wear?",
  "What's your favorite part of foreplay?",
  "What's the most impulsive or bold move you've made on someone?",
  "What's a kink you've recently discovered you have?",
  "What's the sexiest memory you keep coming back to?",
  "What's something you'd only do with someone you really trust?",
  "What's the most turned on you've ever been without actually doing anything?",
  "What's the freakiest thing you've actually done in bed — not just thought about?",
  "Have you ever been caught hooking up? What happened?",
  "What's the most bodies you've had in one week?",
  "Have you ever faked it? How many times and why?",
  "What's the weirdest place you've ever masturbated?",
  "Have you ever sent nudes to the wrong person? What happened?",
  "What's something you've done during sex that you'd never admit to your friends?",
  "What's your body count and are you proud or ashamed?",
  "Have you ever hooked up with someone you definitely shouldn't have? Who?",
  "What's the kinkiest thing someone has asked you to do — and did you do it?",
  "Have you ever been with more than one person at the same time?",
  "What's the longest you've gone at it in one session?",
  "What's something you pretend you're not into but secretly love?",
  "Have you ever recorded yourself or been recorded during sex?",
  "What's the fastest you've ever gone from meeting someone to sleeping with them?",
  "What's a sexual boundary you used to have that you've completely thrown out?",
  "Have you ever sexted someone while you were in a relationship with someone else?",
  "What's the most desperate thing you've ever done because you were horny?",
  "If you could have anyone in this game do anything to you right now, who and what?",
]

export const DARES: string[] = [
  "📸 Take a selfie right now — no fixing anything. Send it to the chat as-is.",
  "📸 Take a photo from the neck down in whatever you're wearing. Send it.",
  "📸 Send your sexiest mirror selfie to the chat. Work your angles.",
  "📸 Take a close-up photo of your lips. Make it as seductive as possible.",
  "📸 Send a photo of your neck and collarbone. Make it look hot.",
  "📸 Take a photo showing off your legs. Send it.",
  "📸 Snap a pic of yourself biting your lip. Send it.",
  "📸 Take a 'just woke up in bed' photo and send it to the chat.",
  "📸 Take a suggestive photo using only shadows and lighting. Send it.",
  "📸 Send a photo of yourself with one less piece of clothing than you have on now.",
  "📸 Take a photo of yourself from behind, looking over your shoulder. Send it.",
  "📸 Show the group the last spicy photo in your camera roll (blur faces if needed).",
  "📸 Take a photo in just your underwear and send it to the chat.",
  "📸 Take a photo of your stomach — shirt pulled up or off. Send it.",
  "📸 Send a chest/cleavage photo to the chat. You decide how much to show.",
  "Run your fingers slowly from your neck down to your waist on camera.",
  "Trace circles on your inner thigh with your fingertips for 15 seconds on camera.",
  "Run your hands slowly through your hair, tilt your head back, and hold it for 10 seconds.",
  "Touch yourself wherever feels good — 20 seconds, on camera, you pick the spot.",
  "Rub the back of your neck slowly with your eyes closed for 15 seconds. Let everyone watch.",
  "Run an ice cube or cold water across your chest on camera and react naturally.",
  "Slowly trace your fingers across your stomach for 15 seconds on camera.",
  "Place your hand on your inner thigh and slide it up as far as you dare. Show the group.",
  "Caress your own arms, shoulders, and neck like someone else is doing it — 20 seconds.",
  "Put your hand under your shirt and run it across your body for 15 seconds on camera.",
  "Run your fingertips along the waistband of your pants or underwear slowly on camera.",
  "Press your hands against your chest and slide them down your body to your hips. Do it slow.",
  "Massage your own thigh slowly for 15 seconds while looking at the camera.",
  "Take off one piece of clothing right now. Show the group.",
  "Choose: lose your shirt or your pants for the next 3 rounds. Send proof.",
  "Do a slow striptease — remove at least one item. Take your time with it.",
  "Show the group your underwear without fully undressing. Get creative.",
  "Undress to your underwear and do a slow spin on camera.",
  "Unbutton or unzip something and leave it open for the rest of the round.",
  "Put on the least amount of clothing you're comfortable with and show the group.",
  "Pull your shirt off over your head as slowly as you can on camera.",
  "Lower your waistband just enough to show your hip bones. Hold it for 10 seconds.",
  "Record a 15-second voice note of your sexiest moan. Send it to the chat.",
  "Whisper into a voice note exactly what you want done to you tonight. Send it.",
  "Say 'I want you' in the most seductive voice you can. Record it and send it.",
  "Do your best fake orgasm for the group. Full commitment — sell it.",
  "Record yourself moaning someone's name the way you'd say it in bed. Send it.",
  "Whisper a dirty fantasy into a voice note — 30 seconds minimum. Send it.",
  "Do a sexy dance for 30 seconds. No laughing — commit to it.",
  "Suck on your finger slowly while looking at the camera for 10 seconds.",
  "Bite your lip and give the camera your best 'come here' eyes for 15 seconds.",
  "Lick your lips slowly and tell the group one thing that makes you weak.",
  "Do a slow, sexy walk across the room on camera.",
  "Demonstrate how you kiss — use the back of your hand. Make it look real.",
  "Lay back and arch your back like something amazing just happened. Hold it 10 seconds.",
  "Blindfold yourself with a shirt or scarf and describe your hottest fantasy for 60 seconds.",
  "Strike your most seductive pose and hold it for 15 seconds. The group rates you 1–10.",
  "Crawl across the bed or floor toward the camera as seductively as you can.",
  "Pretend the camera is someone you're into — seduce it for 20 seconds without speaking.",
  "Lay on your back, close your eyes, and act out exactly how you react when you're being pleased — 15 seconds.",
  "Describe in detail how you like to be touched — where, how slow, how hard. Be specific.",
  "Tell the group your dirtiest fantasy. Leave nothing out.",
  "Describe step by step what you'd do to someone if you had them alone for one hour.",
  "Describe the hottest sexual experience you've ever had. Set the scene.",
  "Tell the group exactly what turns you on the fastest. Be specific.",
  "Describe your body the way you'd want a lover to describe it.",
  "Describe what you'd do on a one-night stand — from the first look to the morning after.",
  "Tell the group the one move you do that always gets a reaction. Demonstrate if you dare.",
  "Describe the last time you touched yourself — what were you thinking about?",
  "Tell the group your biggest bedroom secret — something nobody here knows.",
]

/** BDSM / power-exchange prompts — opt-in per question via the Kink deck. */
export const KINK_TRUTHS: string[] = [
  'Do you want to own me tonight, or be owned — and how absolute should that feel?',
  "What's the filthiest order you've wanted to give me but never dared?",
  "What's the most humiliating praise or degradation that would actually turn you on?",
  "If I cuffed you and told you that you don't get to come, would you thank me or fight it?",
  'Where do you want to be restrained — wrists, ankles, both, collar, blindfold — rank them.',
  "Do you want me to fuck your throat / ride your face until I'm satisfied, even if you're a mess?",
  'What\'s a "no" you\'ve said during sex that you secretly wanted me to push past inside negotiated play?',
  'Do you get harder/wetter from being denied, used, or praised like property?',
  "What's the meanest (hottest) thing I could say while I'm inside you / on top of you?",
  'If I put you on your knees and told you to present, what would "good" look like to you?',
  'Do you want impact — spanking, hair pull, face hold — and how rough?',
  "What's one body part you'd let me claim as mine for the night?",
  "Have you fantasized about being tied and teased until you're shaking? Describe it dirty.",
  'Do you want me to decide when you come, how you come, and whether you come at all?',
  "What's a service act you'd do for me that feels submissive in the best way?",
  'Do you want aftercare soft, or do you want to stay in protocol until I release you?',
  "What's your ruin fantasy: overstimulation, orgasm control, or being left aching?",
  'If I told you to hold still while I used you, how still could you actually stay?',
  "What's a restraint setup you've mentally built for us down to the details?",
  'Do you want me to make you beg properly — full sentences, eye contact, no shortcuts?',
  "What's dirtier to you: being displayed for me, or being hidden and privately destroyed?",
  'Name the exact words you want me to use when I give permission to come.',
  "What's a Dom move that would make you drop into subspace / Domspace fast?",
  'Do you want pain mixed with pleasure, or pure control with almost no pain?',
  'If I put a collar, belt, or my hand on your throat (safe pressure only), what does that do to you?',
]

export const KINK_DARES: string[] = [
  "Kneel. Ask permission to touch me. Don't move until I say yes.",
  'Present: hands behind your back, chest out / ass up — whichever I choose — and hold it.',
  "Let me restrain your wrists. You don't get them back until you earn it.",
  'Blindfold on. Mouth open. Wait for instruction without guessing.',
  'Edge yourself (or me) under orders: stop instantly when I say "stop," even mid-breath.',
  'Get face-fucked / sit on my face for a timed round — I control pace and depth within your limits.',
  'Ask to come. If I say no, thank me and keep going.',
  'Take 15 spanks (or swats) counting each one. Miss a count, we restart.',
  'Hands tied or held: use only your mouth for 3 minutes exactly as directed.',
  "Crawl (or walk on your knees if that's your dynamic) to me and kiss wherever I point.",
  'Hold eye contact while I talk down to you / worship-own you — no looking away.',
  'Let me put you in a hogtie-lite / ankles-to-wrists / belt restraint for 5 minutes of teasing only.',
  "Beg for my cock / cunt / hand in a full filthy paragraph. Rewrite it if I say it's not good enough.",
  "I choose your position. You stay in it while I use you — you don't adjust unless told.",
  'Wear a collar, tie, belt, or my hand as a collar. Address me as agreed (Sir/Goddess/etc.) for 10 minutes.',
  'Overstimulate after orgasm (with consent): keep going for 20–60 seconds after I say "again."',
  'Hands behind your back while I fuck you / ride you. If your hands move, I stop and make you ask to continue.',
  'Let me gag you (cloth/kiss-gag/proper gag if you have one). Tap out = safeword.',
  'Service round: undress me, warm me up, and ask how I want to finish using you.',
  "Press your face into me / between my legs and don't pull away until I release you.",
  'Restraint + denial: tied, touched to the edge 3 times, no orgasm. Then thank me.',
  'Hair pulled back, throat offered, mouth used — controlled, not reckless.',
  'I write a temporary rule on you (marker/lipstick): "Don\'t come," "Mine," "Ask." Obey it for the scene.',
  'Prone bone / bent over / folded — your choice of vulnerable position — and tell me to take you apart.',
  'Endgame: I pick one — fuck you restrained until I\'m done, sit on your face until I come, or edge you until you break etiquette and get punished. You say "yes" and we start.',
]

// The minigame loser's forfeit.
export const FORFEIT = 'Send a sexy photo to the group chat 📸🔥'

// Random prompt for the "surprise me" generator (standard NSFW pool).
export function randomTodPrompt(kind: 'truth' | 'dare'): string {
  const list = kind === 'truth' ? TRUTHS : DARES
  return list[Math.floor(Math.random() * list.length)]
}

export function randomPrompt(kind: 'truth' | 'dare', seed: number): string {
  const list = kind === 'truth' ? TRUTHS : DARES
  return list[Math.abs(seed) % list.length]
}
