// NSFW truth + dare lists for an adults-only (18+) party game.
// Sourced from the Truth or Dare "sexy" mode question lists.
export const TRUTHS: string[] = [
  "What's the most attractive quality in someone that has nothing to do with looks?",
  "What's the best kiss you've ever had and why?",
  "What's something that instantly puts you in the mood?",
  "What's your idea of a perfect date night?",
  "What's the most romantic or flirty thing someone has done for you?",
  "What's a turn-on you're a little embarrassed to admit?",
  "What's the sexiest compliment you've ever received?",
  "What's your favorite way to be touched?",
  "What's something you find attractive that most people don't?",
  "What's the most daring thing you've done for someone you liked?",
  "What's your wildest fantasy you'd actually try?",
  "What's the riskiest place you've ever hooked up or fooled around?",
  "What's the hottest text or DM you've ever sent or received?",
  "What's something that always gets you going no matter what?",
  "What body part on someone else turns you on the most?",
  "What's a song or movie scene that always turns you on?",
  "What's the most spontaneous sexual thing you've ever done?",
  "What's one thing you've always wanted to try in bed?",
  "What's the most attractive outfit you've seen someone wear?",
  "What's your favorite part of foreplay?",
  "What's the most impulsive or bold move you've made on someone?",
  "What's a kink you've recently discovered you have?",
  "What's the sexiest memory you keep coming back to?",
  "What's something you'd only do with someone you really trust?",
  "What's the most turned on you've ever been without actually doing anything?",
  "What's the freakiest thing you've actually done in bed — not just thought about?",
  "Have you ever been caught hooking up? What happened?",
  "What's the most bodies you've had in one week?",
  "Have you ever faked it? How many times and why?",
  "What's the weirdest place you've ever masturbated?",
  "Have you ever sent nudes to the wrong person? What happened?",
  "What's something you've done during sex that you'd never admit to your friends?",
  "What's your body count and are you proud or ashamed?",
  "Have you ever hooked up with someone you definitely shouldn't have? Who?",
  "What's the kinkiest thing someone has asked you to do — and did you do it?",
  "Have you ever been with more than one person at the same time?",
  "What's the longest you've gone at it in one session?",
  "What's something you pretend you're not into but secretly love?",
  "Have you ever recorded yourself or been recorded during sex?",
  "What's the fastest you've ever gone from meeting someone to sleeping with them?",
  "What's a sexual boundary you used to have that you've completely thrown out?",
  "Have you ever sexted someone while you were in a relationship with someone else?",
  "What's the most desperate thing you've ever done because you were horny?",
  "If you could have anyone in this game do anything to you right now, who and what?",
]

export const DARES: string[] = [
  "📸 Take a selfie right now — no fixing anything. Send it to the chat as-is.",
  "📸 Take a photo from the neck down in whatever you're wearing. Send it.",
  "📸 Send your sexiest mirror selfie to the chat. Work your angles.",
  "📸 Take a close-up photo of your lips. Make it as seductive as possible.",
  "📸 Send a photo of your neck and collarbone. Make it look hot.",
  "📸 Take a photo showing off your legs. Send it.",
  "📸 Snap a pic of yourself biting your lip. Send it.",
  "📸 Take a 'just woke up in bed' photo and send it to the chat.",
  "📸 Take a suggestive photo using only shadows and lighting. Send it.",
  "📸 Send a photo of yourself with one less piece of clothing than you have on now.",
  "📸 Take a photo of yourself from behind, looking over your shoulder. Send it.",
  "📸 Show the group the last spicy photo in your camera roll (blur faces if needed).",
  "📸 Take a photo in just your underwear and send it to the chat.",
  "📸 Take a photo of your stomach — shirt pulled up or off. Send it.",
  "📸 Send a chest/cleavage photo to the chat. You decide how much to show.",
  "Run your fingers slowly from your neck down to your waist on camera.",
  "Trace circles on your inner thigh with your fingertips for 15 seconds on camera.",
  "Run your hands slowly through your hair, tilt your head back, and hold it for 10 seconds.",
  "Touch yourself wherever feels good — 20 seconds, on camera, you pick the spot.",
  "Rub the back of your neck slowly with your eyes closed for 15 seconds. Let everyone watch.",
  "Run an ice cube or cold water across your chest on camera and react naturally.",
  "Slowly trace your fingers across your stomach for 15 seconds on camera.",
  "Place your hand on your inner thigh and slide it up as far as you dare. Show the group.",
  "Caress your own arms, shoulders, and neck like someone else is doing it — 20 seconds.",
  "Put your hand under your shirt and run it across your body for 15 seconds on camera.",
  "Run your fingertips along the waistband of your pants or underwear slowly on camera.",
  "Press your hands against your chest and slide them down your body to your hips. Do it slow.",
  "Massage your own thigh slowly for 15 seconds while looking at the camera.",
  "Take off one piece of clothing right now. Show the group.",
  "Choose: lose your shirt or your pants for the next 3 rounds. Send proof.",
  "Do a slow striptease — remove at least one item. Take your time with it.",
  "Show the group your underwear without fully undressing. Get creative.",
  "Undress to your underwear and do a slow spin on camera.",
  "Unbutton or unzip something and leave it open for the rest of the round.",
  "Put on the least amount of clothing you're comfortable with and show the group.",
  "Pull your shirt off over your head as slowly as you can on camera.",
  "Lower your waistband just enough to show your hip bones. Hold it for 10 seconds.",
  "Record a 15-second voice note of your sexiest moan. Send it to the chat.",
  "Whisper into a voice note exactly what you want done to you tonight. Send it.",
  "Say 'I want you' in the most seductive voice you can. Record it and send it.",
  "Do your best fake orgasm for the group. Full commitment — sell it.",
  "Record yourself moaning someone's name the way you'd say it in bed. Send it.",
  "Whisper a dirty fantasy into a voice note — 30 seconds minimum. Send it.",
  "Do a sexy dance for 30 seconds. No laughing — commit to it.",
  "Suck on your finger slowly while looking at the camera for 10 seconds.",
  "Bite your lip and give the camera your best 'come here' eyes for 15 seconds.",
  "Lick your lips slowly and tell the group one thing that makes you weak.",
  "Do a slow, sexy walk across the room on camera.",
  "Demonstrate how you kiss — use the back of your hand. Make it look real.",
  "Lay back and arch your back like something amazing just happened. Hold it 10 seconds.",
  "Blindfold yourself with a shirt or scarf and describe your hottest fantasy for 60 seconds.",
  "Strike your most seductive pose and hold it for 15 seconds. The group rates you 1–10.",
  "Crawl across the bed or floor toward the camera as seductively as you can.",
  "Pretend the camera is someone you're into — seduce it for 20 seconds without speaking.",
  "Lay on your back, close your eyes, and act out exactly how you react when you're being pleased — 15 seconds.",
  "Describe in detail how you like to be touched — where, how slow, how hard. Be specific.",
  "Tell the group your dirtiest fantasy. Leave nothing out.",
  "Describe step by step what you'd do to someone if you had them alone for one hour.",
  "Describe the hottest sexual experience you've ever had. Set the scene.",
  "Tell the group exactly what turns you on the fastest. Be specific.",
  "Describe your body the way you'd want a lover to describe it.",
  "Describe what you'd do on a one-night stand — from the first look to the morning after.",
  "Tell the group the one move you do that always gets a reaction. Demonstrate if you dare.",
  "Describe the last time you touched yourself — what were you thinking about?",
  "Tell the group your biggest bedroom secret — something nobody here knows.",
]

// The minigame loser's forfeit.
export const FORFEIT = 'Send a sexy photo to the group chat 📸🔥'

// Random prompt for the "surprise me" generator.
export function randomTodPrompt(kind: 'truth' | 'dare'): string {
  const list = kind === 'truth' ? TRUTHS : DARES
  return list[Math.floor(Math.random() * list.length)]
}

export function randomPrompt(kind: 'truth' | 'dare', seed: number): string {
  const list = kind === 'truth' ? TRUTHS : DARES
  return list[Math.abs(seed) % list.length]
}
